return {
	"NeogitOrg/neogit",
	event = "VeryLazy",
	config = true,
	version = "*",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
	},
	opts = {
		disable_context_highlighting = true,
		disable_insert_on_commit = true,
		filewatcher = {
			interval = 500,
			enabled = true,
		},
		use_default_keymaps = false,
		signs = {
			hunk = { "", "" },
			item = { "", "" },
			section = { "", "" },
		},
		-- Each Integration is auto-detected through plugin presence, however, it can be disabled by setting to `false`
		integrations = {
			telescope = true,
			diffview = false,
			fzf_lua = false,
		},
		mappings = {
			commit_editor_I = {},
			rebase_editor_I = {},
			commit_editor = {
				["q"] = "Close",
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
			},
			rebase_editor = {
				["p"] = "Pick",
				["r"] = "Reword",
				["e"] = "Edit",
				["s"] = "Squash",
				["f"] = "Fixup",
				["x"] = "Execute",
				["d"] = "Drop",
				["b"] = "Break",
				["q"] = "Close",
				["<cr>"] = "OpenCommit",
				["gk"] = "MoveUp",
				["gj"] = "MoveDown",
				["<c-c><c-c>"] = "Submit",
				["<c-c><c-k>"] = "Abort",
			},
			finder = {
				["<cr>"] = "Select",
				["<esc>"] = "Close",
				["<tab>"] = "MultiselectToggleNext",
				["<s-tab>"] = "MultiselectTogglePrevious",
				["<c-j>"] = "NOP",
			},
			popup = {
				["g?"] = "HelpPopup",
				["A"] = false,
				["D"] = false,
				["M"] = "RemotePopup",
				["P"] = "PushPopup",
				["X"] = "ResetPopup",
				["Z"] = "StashPopup",
				["b"] = "BranchPopup",
				["c"] = "CommitPopup",
				["f"] = "FetchPopup",
				["l"] = "LogPopup",
				["m"] = "MergePopup",
				["p"] = "PullPopup",
				["r"] = false,
				["v"] = false,
			},
			status = {
				["q"] = "Close",
				["I"] = "InitRepo",
				["1"] = "Depth1",
				["2"] = "Depth2",
				["3"] = "Depth3",
				["4"] = "Depth4",
				["<tab>"] = "Toggle",
				["x"] = "Discard",
				["ss"] = "Stage",
				["su"] = "StageUnstaged",
				["sa"] = "StageAll",
				["u"] = "Unstage",
				["U"] = "UnstageStaged",
				["Y"] = "YankSelected",
				["R"] = "RefreshBuffer",
				["gf"] = "GoToFile",
				["<c-v>"] = "VSplitOpen",
				["<c-x>"] = "SplitOpen",
				["<c-t>"] = "TabOpen",
				["{"] = "GoToPreviousHunkHeader",
				["}"] = "GoToNextHunkHeader",
				["d"] = false,
				["$"] = false,
			},
		},
	},
}
