local opts = {
	sync_install = true,
	ensure_installed = {
		"bash",
		"comment",
		"css",
		"diff",
		"dockerfile",
		"fish",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"go",
		"godot_resource",
		"gomod",
		"gosum",
		"gowork",
		"hcl",
		"html",
		"ini",
		"javascript",
		"jq",
		"json",
		"jsonc",
		"jsonnet",
		"lua",
		"luadoc",
		"make",
		"markdown",
		"markdown_inline",
		"mermaid",
		"passwd",
		"promql",
		"proto",
		"python",
		"regex",
		"requirements",
		"rst",
		"scheme",
		"sql",
		"ssh_config",
		"strace",
		"terraform",
		"toml",
		"tsv",
		"typescript",
		"udev",
		"yaml",
	},
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "gnn",
			node_decremental = "grm",
			node_incremental = "grn",
			scope_incremental = "grc",
			-- init_selection = "<C-s>",
			-- node_incremental = "<C-s>",
			-- scope_incremental = false,
			-- node_decremental = "<BS>",
		},
	},
	indent = {
		enable = true,
	},
}

return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	build = ":TSUpdate",
	init = function()
		require("nvim-treesitter.configs").setup(opts)
	end,
}
